### ISSUE TITLE
Can xamarin call the method inside

### ISSUE THREAD

**Issue by LinuxAndOracle** [tkp1n/AesNi#2]
I want to call the method in aesni class from xamarin, and if I can, what should I do?

**Comment by tkp1n** [comment]
AesNi is based on hardware intrinsics for x86 CPUs which are (to my knowledge) not supported on typical mobile CPUs. Also, AesNi targets .NET Core 3.0 and will not work on Xamarin (which is based on Mono) as it stands today. Maybe it will, once .NET 5 is around.

I‘d just use the built-in AES routines that ship with the framework and make sure you select the proper mode of use to achieve your goals. As an example: AES-GCM ensures both confidentiality and authenticity when handled correctly (incl. the use of a unique IV).

I could imagine, that there are platform specific crypto APIs for mobile, but I‘m no expert in mobile development.
