### ISSUE TITLE
Minor AESNI key schedule optimization

### ISSUE THREAD

**Issue by peterdettman** [tkp1n/AesNi#4]
Two of the shifted-xors here can be replaced by a single one of 8 bits:

https://github.com/tkp1n/AesNi/blob/4b4c42f0b4a18564dd480aaec26dc89b0a91646a/AesNi/Aes128Key.cs#L88-L90

e.g.:

```
key = Xor(key, ShiftLeftLogical128BitLane(key, 8));
key = Xor(key, ShiftLeftLogical128BitLane(key, 4));

```
(or indeed in reverse order).

Of course this also applies to the Aes192Key and Aes256Key.

**Comment by tkp1n** [comment]
Good call, thank you for reporting this.
I've improved the key expansion source with ba717772ec7e3cbf11321f699412a2cbe7353cda

### Before
|                Method |     Mean |    Error |   StdDev |
|---------------------- |---------:|---------:|---------:|
| Aes128BitKeyExpansion | 65.04 ns | 0.427 ns | 0.357 ns |
| Aes192BitKeyExpansion | 64.80 ns | 0.587 ns | 0.458 ns |
| Aes256BitKeyExpansion | 82.36 ns | 0.340 ns | 0.318 ns |


### After
|                Method |     Mean |    Error |   StdDev |
|---------------------- |---------:|---------:|---------:|
| Aes128BitKeyExpansion | 62.29 ns | 0.215 ns | 0.191 ns |
| Aes192BitKeyExpansion | 61.24 ns | 0.085 ns | 0.071 ns |
| Aes256BitKeyExpansion | 78.53 ns | 0.167 ns | 0.156 ns |
